<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64</Platforms>
    <AssemblyName>AutoAffectionSkip</AssemblyName>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="bin\Debug\**" />
    <Compile Remove="bin\x64\Debug\**" />
    <EmbeddedResource Remove="bin\Debug\**" />
    <EmbeddedResource Remove="bin\x64\Debug\**" />
    <None Remove="bin\Debug\**" />
    <None Remove="bin\x64\Debug\**" />
    <Page Remove="bin\Debug\**" />
    <Page Remove="bin\x64\Debug\**" />
  </ItemGroup>

  <ItemGroup>
    <None Update="resource\images\exit_momotalk.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="resource\images\menu_btn.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="resource\images\message_count_box.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="resource\images\message_icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="resource\images\message_reply_logo_0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="resource\images\message_story_enter_btn.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="resource\images\momotalk_icon_0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="resource\images\momotalk_logo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="resource\images\ok_btn.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="resource\images\pyroxene.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="resource\images\skip_btn.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="resource\images\story_enter_btn.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Remove="app.ico"/>
    <Resource Include="app.ico"/>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="bin\x64\Debug\net8.0-windows\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="bin\x64\Release\net8.0-windows\AasCore.dll" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ModernWpfUI" Version="0.9.6" />
  </ItemGroup>

</Project>
